version: '3.8'

services:
   local-mysql:
     image: mysql:8.3.0
     volumes:
       - mysql_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: joomla
       MYSQL_DATABASE: joomla
       MYSQL_USER: joomla
       MYSQL_PASSWORD: joomla

   joomla:
     depends_on:
       - local-mysql
     image: joomla:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       JOOMLA_DB_HOST: local-mysql:3306
       JOOMLA_DB_USER: joomla
       JOOMLA_DB_PASSWORD: joomla
       JOOMLA_DB_NAME: joomla
volumes:
    mysql_data: {}